export const ADD_EXECUTION_SUCCESS  = "ADD_EXECUTION_SUCCESS";
export const FIND_ALL_RECURRING_TASKS_SUCCESS  = "FIND_ALL_RECURRING_TASKS_SUCCESS";
export const CREATE_RECURRING_TASK_SUCCESS = "CREATE_RECURRING_TASK_SUCCESS";
export const UPDATE_RECURRING_TASK_SUCCESS = "UPDATE_RECURRING_TASK_SUCCESS";
export const DELETE_RECURRING_TASK_SUCCESS = "DELETE_RECURRING_TASK_SUCCESS";
export const AJAX_CALL_STARTED = "AJAX_CALL_STARTED";
export const AJAX_CALL_ENDED = "AJAX_CALL_ENDED";